name: Testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [dev, main]

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: npm ci
      - run: npm run test_ci
